webserverPort: 8080

logLevel: info

jsonExporter:
  enabled: true

prometheusExporter:
  enabled: true

influxDbExporter:
  enabled: false
  server: 1.2.3.4
  port: 8086
  database: database(bucket)
  measurement: measurement
  token: token
  org : org

mqtt:
  enabled: false
  brokerAddress: 1.2.3.4
  brokerPort: 1883
  username: username
  password: password
  clientId: weather-exporter
  topicPrefix: weather
