version: '3.8'

services:
  weather-exporter:
    build: .
    environment:
      - WEATHER_EXPORTER_WEBSERVERPORT=8082
      - WEATHER_EXPORTER_LOGLEVEL=info
      - WEATHER_EXPORTER_JSONEXPORTER_ENABLED=true
      - WEATHER_EXPORTER_PROMETHEUSEXPORTER_ENABLED=true
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_ENABLED=false
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_SERVER=1.2.3.4
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_PORT=8086
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_ORG=<org>
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_TOKEN=<token> # or <username>:<password>
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_DATABASE=<database(bucket)>
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_MEASUREMENT=<measurement>
      - WEATHER_EXPORTER_MQTT_ENABLED=false
      - WEATHER_EXPORTER_MQTT_BROKERADDRESS=1.2.3.4
      - WEATHER_EXPORTER_MQTT_BROKERPORT=1883
      - WEATHER_EXPORTER_MQTT_USERNAME=username
      - WEATHER_EXPORTER_MQTT_PASSWORD=password
      - WEATHER_EXPORTER_MQTT_CLIENTID=weather-exporter
      - WEATHER_EXPORTER_MQTT_TOPICPREFIX=weather
    ports:
      - "8080:8080"
