version: '3.8'

services:
  weather-exporter:
    build: .
    environment:
      - WEATHER_EXPORTER_WEBSERVERPORT=8080
      - WEATHER_EXPORTER_LOGLEVEL=info
      - WEATHER_EXPORTER_JSONEXPORTER_ENABLED=true
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_ENABLED=true
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_SERVER=influx-db
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_PORT=8086
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_ORG=org
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_TOKEN=$INFLUX_DB_TOKEN
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_DATABASE=$INFLUX_DB_BUCKET
      - WEATHER_EXPORTER_INFLUXDBEXPORTER_MEASUREMENT=$INFLUX_DB_MEASUREMENT
    ports:
      - "8083:8080"
  influx-db:
    container_name: influx-db
    image: influxdb:2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_DB_USER:?Set it to the influx db username}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_DB_PASSWORD:?Set it to the influx db password}
      - DOCKER_INFLUXDB_INIT_ORG=org
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_DB_BUCKET:?Set it to the influx db database}
    ports:
      - 8086:8086
    volumes:
      - influxdb-storage-data:/var/lib/influxdb2
      - influxdb-storage-config:/etc/influxdb2
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - INFLUX_DB_TOKEN=$INFLUX_DB_TOKEN
      - INFLUX_DB_BUCKET=$INFLUX_DB_BUCKET
      - INFLUX_DB_MEASUREMENT=$INFLUX_DB_MEASUREMENT
      - GF_INSTALL_PLUGINS=operato-windrose-panel
      - GF_AUTH_ANONYMOUS_ENABLED=true

volumes:
  grafana-storage:
  influxdb-storage-data:
  influxdb-storage-config:
